apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-web
  template:
    metadata:
      labels:
        app: nextjs-web
    spec:
      containers:
      - name: nextjs-web
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.anycompany.com"
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-web
spec:
  selector:
    app: nextjs-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
