apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgres://user:mypassword@${DB_INSTANCE_CONNECTION_NAME}/mydatabase"
        - name: REDIS_HOST
          value: "redis-master.redis.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: node-api
spec:
  selector:
    app: node-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: ${EXTERNAL_IP}
