apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-native
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-native
  template:
    metadata:
      labels:
        app: react-native
    spec:
      containers:
      - name: react-native
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-native:latest
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          value: "https://api.anycompany.com"
---
apiVersion: v1
kind: Service
metadata:
  name: react-native
spec:
  selector:
    app: react-native
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
